In [5]:
import numpy as np

'''
Iterate over each number in the input vector n times, n being the number of columns in the o/p matrix and output an 
intermediate vector. Use different order formula based on increasing and decreasing condition.
Reshape the intermediate vector using the size of the input vector (rows) and n (columns) to generate the o/p matrix.
'''

def gen_vander_matrix(ipvector, n, increasing=False):
    if not increasing:
        op_matrix = np.array([x ** (n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matrix = np.array([x ** i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
        
    return op_matrix

In [6]:
gen_vander_matrix(ipvector=np.array([1,2,3,5]), n=4, increasing=False)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [7]:
gen_vander_matrix(ipvector=np.array([1,2,3,5]), n=4, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [4]:
np.vander(x = np.array([1,2,3,5]), N=4, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [23]:
def moving_average(a, n=3):
# we use np.cumsum to get a cumulative sum of the numbers    
    asum = np.cumsum(a, dtype=float)
# we are breaking the array as per desired number which is 'n' in our function and subtracting elements to get the desired result.
    asum[n:] = asum[n:] - asum[:-n]
    return asum[n-1:] / n

In [26]:
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
a1 = np.array(a)
# rounding off the results to two digits
np.array(moving_average(a = a1, n=3)).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])